Repository mju-likelion/custard-pudding, pull requests merged in 2024-02, with the labels that each got.

#23 [Feature/#22] 메인페이지 스크롤 바
  src/components/mainPage/ScrollBar.js
  src/components/mainPage/Wave.js
  src/messages/part.js
  src/pages/Main.js
Labels: 💎 feature

#20 [Feature/#14] ApplyWrite 페이지 구현
  src/components/Header/Header.js
  src/components/PageLayout.js
  src/components/writePage/ApplyAnswer.js
  src/components/writePage/InputLabelList.js
  src/components/writePage/UserInfoInput.js
  src/pages/ApplyWrite/index.js
Labels: 💎 feature

#30 [Feature/#29] UI 깨짐 수정
  public/index.html
  src/components/PageLayout.js
  src/components/RoutesContainer.js
  src/components/mainPage/PartCard.js
  src/components/mainPage/ScrollBar.js
  src/components/mainPage/Wave.js
  src/styles/GlobalStyle.js
Labels: 🔨 fix, ♻️ refactor

#27 [Feature/#26] 지원 확인 페이지 레이아웃 설정
  public/index.html
  src/pages/Apply.js
  src/pages/Check.js
Labels: 💎 feature

#32 [Feature/#18] Toast
  package.json
  src/components/Footer.js
  src/components/mainPage/CopyMail.js
  src/components/mainPage/Toast.js
  yarn.lock
Labels: 💎 feature

#35 [Feature/#28] introduction page validation 구현
  src/components/Header/Header.js
  src/components/RoutesContainer.js
  src/components/writePage/ApplyAnswer.js
  src/components/writePage/InputLabelList.js
  src/components/writePage/UserInfoInput.js
  src/pages/ApplyWrite/InfoInputBox.js
  src/pages/ApplyWrite/InfoInputData.js
  src/pages/ApplyWrite/Introduction.js
  src/pages/ApplyWrite/IntroductionData.js
  src/pages/ApplyWrite/index.js
  src/validation/writeValidationSchema.js
Labels: 💎 feature

#37 [Feature/#34] 지원 여부 확인 페이지 구현
  src/assets/imgs/card_tag.svg
  src/assets/imgs/checked.svg
  src/assets/imgs/failed.svg
  src/components/checkPage/CheckCard.js
  src/components/checkPage/resultData.js
  src/pages/Check.js
Labels: 💎 feature

#40 [Feature/#38] 404, 지원 완료 페이지 구현
  src/assets/imgs/Lion.svg
  src/assets/imgs/bubble.svg
  src/assets/imgs/tail.svg
  src/components/Button/BigButton.js
  src/components/PageLayout.js
  src/components/RoutesContainer.js
  src/pages/Complete.js
  src/pages/Main.js
  src/pages/NotFound.js
Labels: 💎 feature

#41 [Feature/#39] 지원 여부 확인 결과에 따른 화면을 렌더링
  src/api/Axios.js
  src/assets/imgs/reject.svg
  src/components/checkPage/CheckCard.js
  src/components/checkPage/resultData.js
  src/pages/Apply.js
  src/pages/Check.js
  src/pages/Main.js
Labels: 💎 feature, ♻️ refactor

#43 [Feature/#42] 반응형에 따른 버튼 컴포넌트 크기 변화 추가
  src/components/Button/BigButton.js
Labels: 💎 feature

#48 [Feature/#47] 지원 성공시 폭죽 효과 추가
  package.json
  src/Confetti.js
  src/pages/Complete.js
  yarn.lock
Labels: 💎 feature

#53 [Feature/#51] 지원 확인 결과 실제 학번 값으로 변경
  src/components/checkPage/CheckCard.js
  src/components/checkPage/resultData.js
  src/pages/Apply.js
  src/pages/Check.js
Labels: 💎 feature

#57 [Feature/#56] 지원서 작성 페이지 제출하기 버튼 구현
  src/components/Button/BigButton.js
  src/components/writePage/SubmitButton.js
  src/pages/ApplyWrite/index.js
  src/pages/Main.js
Labels: 💎 feature

#62 [Feature/#55] title, favicon 변경
  public/index.html
  public/lion.ico
Labels: 💎 feature

#61 [feature/#60] 가로 스크롤 방지
  src/styles/GlobalStyle.js
Labels: 🔨 fix

#64 [Feature/#63] statusCode 값 수정
  src/pages/Apply.js
  src/pages/Check.js
Labels: 🔨 fix

#67 [Feature/#65] 오픈 채팅
  src/assets/imgs/lion.png
  src/assets/imgs/openchat_lion.svg
  src/components/mainPage/OpenChat.js
  src/pages/Main.js
Labels: 💎 feature

#72 [Feature/#71] CardLanyard 컴포넌트의 디자인 변경
  src/assets/imgs/card_string_test.svg
  src/components/CardLanyard/CardLanyard.js
Labels: 🔨 fix

#74 [Feature/#66] 페이지 이동시 not found 발생 해결
  public/_redirects
Labels: 💎 feature

#80 [Feature/#79] svg 파일 변경
  src/assets/imgs/apply_reject.svg
  src/assets/imgs/check_fail.svg
  src/assets/imgs/check_success.svg
  src/assets/imgs/checked.svg
  src/assets/imgs/failed.svg
  src/assets/imgs/letter.svg
  src/assets/imgs/reject.svg
  src/components/checkPage/CheckCard.js
  src/components/checkPage/resultData.js
  src/pages/Apply.js
Labels: 🔨 fix

#82 [Feature/#81] 스크롤 바 헤더에 가리는 문제 해결 및 사이즈 수정
  src/components/mainPage/OpenChat.js
  src/components/mainPage/ScrollBar.js
  src/components/mainPage/Wave.js
Labels: 🔨 fix

#84 [Feature/#75] 지원 결과 여부 확인 렌더링 속도 개선
  src/assets/imgs/card_tag_upload.svg
  src/components/checkPage/CheckCard.js
  src/components/checkPage/resultData.js
Labels: ♻️ refactor

#78 [Feature/#54] 메인페이지 내용 수정
  src/messages/part.js
Labels: 💎 feature

#86 [Feature/#85] 카드 css 깨짐 수정
  src/assets/imgs/card_string_bg.svg
  src/components/CardLanyard/CardLanyard.js
Labels: 🔨 fix

#90 [Feature/#76] textarea focus & maxLength 해결
  src/api/ApplyWrite.js
  src/components/writePage/HomeworkBox.js
  src/components/writePage/InfoInputBox.js
  src/components/writePage/PersonalAgreeBox.js
  src/components/writePage/SubmitButton.js
  src/components/writePage/UserInfoInput.js
  src/pages/ApplyWrite/data/HomeworkData.js
  src/pages/ApplyWrite/index.js
  src/validation/writeValidationSchema.js
Labels: 💎 feature

#92 [Feature/#91] 404 페이지 디자인 수정
  src/assets/imgs/hi_lion.svg
  src/pages/NotFound.js
Labels: ♻️ refactor

#89 [Feature/#88] fix warning
  src/components/Button/BigButton.js
  src/pages/Apply.js
Labels: 🔨 fix, ♻️ refactor

#94 [Feature/#93] edit scrollbar
  src/components/mainPage/ScrollBar.js
  src/styles/GlobalStyle.js
Labels: 🔨 fix

#98 [Feature/#96] click limit
  src/api/ApplyWrite.js
  src/components/checkPage/SmallButton.js
  src/pages/Apply.js
  src/pages/ApplyWrite/index.js
  src/pages/Check.js
Labels: 🔨 fix, 💎 feature

#99 [Feature/#97] 메인 페이지의 이미지 렌더링 속도 개선
  src/pages/Main.js
Labels: ♻️ refactor

#101 [Feature/#100] 웹 파트 과제 파일 삭제 기능 추가 - #100
  src/components/writePage/HomeworkBox.js
  src/pages/ApplyWrite/index.js
Labels: 🔨 fix, 💎 feature

#103 [Feature/#102] 전체 CSS 크기 및 간격 수정
  src/api/ApplyWrite.js
  src/assets/imgs/error_lion.svg
  src/components/NotFound/ErrorInfo.js
  src/components/NotFound/ErrorInfoMobile.js
  src/components/NotFound/ErrorInfoTablet.js
  src/components/checkPage/CheckCard.js
  src/components/checkPage/Input.js
  src/components/checkPage/SmallButton.js
  src/components/mainPage/BigButton.js
  src/components/writePage/HomeworkBox.js
  src/components/writePage/PersonalAgreeBox.js
  src/messages/part.js
  src/pages/Apply.js
  src/pages/ApplyWrite/data/HomeworkData.js
  src/pages/ApplyWrite/index.js
  src/pages/Check.js
  src/pages/Main.js
  src/pages/NotFound.js
  src/pages/NotFound/data/ErrorData.js
  src/pages/NotFound/index.js
  src/styles/Theme.js
  src/validation/writeValidationSchema.js
Labels: 🔨 fix

#106 [Feature]date validation
  src/pages/Apply.js
  src/pages/ApplyWrite/index.js
Labels: 💎 feature
