Repository mju-likelion/custard-pudding, pull requests merged in 2024-01, with the labels that each got.

#6 [Feature/#4] 버튼 컴포넌트 제작
  src/components/Button/BigButton.js
  src/components/checkPage/SmallButton.js
  src/styles/GlobalStyle.js
Labels: 💎 feature

#8 [Feature/#7] 지원 확인 학생증 구현
  .eslintrc.json
  src/assets/imgs/big_cardLanyard.svg
  src/assets/imgs/big_card_lanyard.svg
  src/assets/imgs/card_string.svg
  src/assets/imgs/small_card_string.svg
  src/components/CardLanyard/CardLanyard.js
  src/components/checkPage/Input.js
  src/components/checkPage/SubTitle.js
  src/pages/Apply.js
  src/pages/Check.js
Labels: 💎 feature

#12 [Feature/#3] 메인페이지
  src/assets/imgs/card_ring.svg
  src/assets/imgs/letter.svg
  src/assets/imgs/react_icon.svg
  src/assets/imgs/spring_boot_icon.svg
  src/components/PageLayout.js
  src/components/mainPage/AssignmentBox.js
  src/components/mainPage/PartCard.js
  src/messages/part.js
  src/pages/Main.js
  src/styles/Theme.js
Labels: 💎 feature, ♻️ refactor

#13 [Feature/#11] 지원 페이지 반응형 구현
  src/components/CardLanyard/CardLanyard.js
  src/components/checkPage/Input.js
  src/components/checkPage/SubTitle.js
  src/pages/Apply.js
  src/pages/Check.js
  src/styles/Theme.js
Labels: 🔨 fix, 💎 feature
